//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabalhoClienteASPMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public long CD_CLIENTE { get; set; }
        public string NM_CLIENTE { get; set; }
        public string DS_EMAIL { get; set; }
        public string CD_SEXO { get; set; }
        public decimal VL_SALDO_CREDITOS { get; set; }
        public string DS_LOGRADOURO { get; set; }
        public Nullable<int> NR_LOGRADOURO { get; set; }
        public string DS_COMPLEMENTO { get; set; }
        public string NM_BAIRRO { get; set; }
        public string NM_CIDADE { get; set; }
        public string SG_ESTADO { get; set; }
        public string NR_CEP { get; set; }
    }
}
